// frontend/src/components/Sidebar.vue
<template>
  <div :class="['sidebar', { collapsed: isCollapsed }]">
    <Button
      @click="toggleSidebar"
      class="toggle-btn my-btn"
    >
      {{ isCollapsed ? '→' : '←' }}
    </Button>

    <!-- 展开时的菜单 -->
    <ul v-if="!isCollapsed" class="menu expanded-menu">
      <li class="menu-item" @click="navigateTo('home')">
        <img src="/home-icon.svg" alt="主页" class="menu-icon" />
        <span class="menu-text">主页</span>
      </li>
      <li class="menu-item" @click="navigateTo('projects')">
        <img src="/projects-icon.svg" alt="导航" class="menu-icon" />
        <span class="menu-text">导航</span>
      </li>
      <li class="menu-item" @click="navigateTo('profile')">
        <img src="/profile-icon.svg" alt="个人简介" class="menu-icon" />
        <span class="menu-text">个人简介</span>
      </li>
      <li class="menu-item" @click="navigateTo('blog')">
        <img src="/blog-icon.svg" alt="技术博客" class="menu-icon" />
        <span class="menu-text">技术博客</span>
      </li>
      <li class="menu-item" @click="openExternal('https://bufftracker.hezhili.online/')">
        <img src="/buff-tracker-icon.svg" alt="Buff Tracker" class="menu-icon" />
        <span class="menu-text">Buff Tracker</span>
      </li>
      <li class="menu-item" @click="navigateTo('contact')">
        <img src="/contact-icon.svg" alt="联系" class="menu-icon" />
        <span class="menu-text">联系</span>
      </li>
    </ul>

    <!-- 收缩时的图标菜单 -->
    <ul v-else class="menu collapsed-menu">
      <li class="menu-item collapsed-item" title="主页" @click="navigateTo('home')">
        <img src="/home-icon.svg" alt="主页" class="menu-icon collapsed-icon" />
      </li>
      <li class="menu-item collapsed-item" title="导航" @click="navigateTo('projects')">
        <img src="/projects-icon.svg" alt="导航" class="menu-icon collapsed-icon" />
      </li>
      <li class="menu-item collapsed-item" title="个人简介" @click="navigateTo('profile')">
        <img src="/profile-icon.svg" alt="个人简介" class="menu-icon collapsed-icon" />
      </li>
      <li class="menu-item collapsed-item" title="技术博客" @click="navigateTo('blog')">
        <img src="/blog-icon.svg" alt="技术博客" class="menu-icon collapsed-icon" />
      </li>
      <li class="menu-item collapsed-item" title="Buff Tracker" @click="openExternal('https://bufftracker.hezhili.online/')">
        <img src="/buff-tracker-icon.svg" alt="Buff Tracker" class="menu-icon collapsed-icon" />
      </li>
      <li class="menu-item collapsed-item" title="联系" @click="navigateTo('contact')">
        <img src="/contact-icon.svg" alt="联系" class="menu-icon collapsed-icon" />
      </li>
    </ul>
  </div>
</template>

<script>
import { useSidebar } from '../composables/useSidebar.js'
import Button from './Button.vue'
import '../css/sidebar.css'

export default {
  name: 'Sidebar',
  components: {
    Button
  },
  emits: ['navigate'],
  setup(props, { emit }) {
    const { isCollapsed, toggleSidebar } = useSidebar()

    const navigateTo = (view) => {
      console.log('侧边栏点击:', view)
      emit('navigate', view)
    }

    const openExternal = (url) => {
      window.open(url, '_blank')
    }

    return {
      isCollapsed,
      toggleSidebar,
      navigateTo,
      openExternal
    }
  }
}
</script>

// frontend/src/components/Sidebar.tsx
import { useEffect, useState } from "react";
import "./Sidebar.css";

interface SidebarProps {
  activeView: string;
  onNavigate: (view: string) => void;
  onCollapsedChange?: (collapsed: boolean) => void;
}

type NavItem = {
  key: string;
  label: string;
  icon: string;
};

const navItems: NavItem[] = [
  { key: "home", label: "首页", icon: "01" },
  { key: "projects", label: "项目", icon: "02" },
  { key: "contact", label: "联系", icon: "03" },
];

function Sidebar({ activeView, onNavigate, onCollapsedChange }: SidebarProps) {
  const [isCollapsed, setIsCollapsed] = useState(false);

  useEffect(() => {
    onCollapsedChange?.(isCollapsed);
  }, [isCollapsed, onCollapsedChange]);

  return (
    <div className={`sidebar ${isCollapsed ? "collapsed" : ""}`}>
      <div className="sidebar-top">
        <button
          onClick={() => setIsCollapsed((prev) => !prev)}
          className="toggle-btn"
          type="button"
          aria-label="toggle sidebar"
        >
          {isCollapsed ? "→" : "←"}
        </button>
        {!isCollapsed && (
          <div className="brand-block">
            <div className="brand-title">HZL</div>
            <div className="brand-subtitle">Project Console</div>
          </div>
        )}
      </div>

      <nav className="menu" aria-label="main nav">
        {navItems.map((item) => (
          <button
            key={item.key}
            className={`menu-item ${activeView === item.key ? "active" : ""}`}
            onClick={() => onNavigate(item.key)}
            title={item.label}
            type="button"
          >
            <span className="menu-icon">{item.icon}</span>
            {!isCollapsed && <span className="menu-text">{item.label}</span>}
          </button>
        ))}
      </nav>

      {!isCollapsed && (
        <div className="sidebar-footer">
          <a href="https://github.com/Shr1mpTop" target="_blank" rel="noopener noreferrer">
            GitHub
          </a>
          <a href="https://bufftracker.hezhili.online/" target="_blank" rel="noopener noreferrer">
            Buff Tracker
          </a>
        </div>
      )}
    </div>
  );
}

export default Sidebar;
