// frontend/src/App.tsx
import { useState } from "react";
import Sidebar from "./components/Sidebar";
import MatrixBackground from "./components/MatrixBackground";
import Home from "./components/Home";
import Projects from "./components/Projects";
import BuffotteReport from "./components/BuffotteReport";
import About from "./components/About";
import Blog from "./components/Blog";
import PostDetail from "./components/PostDetail";
import Contact from "./components/Contact";
import "./App.css";

function App() {
  const [currentView, setCurrentView] = useState("home");
  const [selectedPost, setSelectedPost] = useState(null);

  const handleNavigate = (view: string, post?: any) => {
    setCurrentView(view);
    if (post) setSelectedPost(post);
  };

  const renderView = () => {
    switch (currentView) {
      case "home":
        return <Home />;
      case "projects":
        return <Projects onNavigate={handleNavigate} />;
      case "buffotte":
        return <BuffotteReport />;
      case "profile":
        return <About />;
      case "blog":
        return <Blog onNavigate={handleNavigate} />;
      case "blog-detail":
        return <PostDetail post={selectedPost} onNavigate={handleNavigate} />;
      case "contact":
        return <Contact />;
      default:
        return <Home />;
    }
  };

  return (
    <div className="app">
      <MatrixBackground />
      <Sidebar onNavigate={handleNavigate} />
      <main className="main-content">{renderView()}</main>
    </div>
  );
}

export default App;

// frontend/src/App.vue
<template>
  <div class="app">
    <MatrixBackground />
    <Sidebar @navigate="handleNavigate" />
    <main class="main-content">
      <!-- 主页内容 -->
      <Home v-if="currentView === 'home'" />

  <!-- 项目页面 -->
  <Projects v-else-if="currentView === 'projects'" @navigate="handleNavigate" />

      <!-- Buffotte 报告 -->
      <BuffotteReport v-else-if="currentView === 'buffotte'" />

      <!-- 个人简介页面 -->
      <About v-else-if="currentView === 'profile'" />

      <!-- 技术博客页面 -->
      <Blog v-else-if="currentView === 'blog'" @navigate="handleNavigate" />

      <!-- 博客详情页面 -->
      <PostDetail v-else-if="currentView === 'blog-detail'" :post="selectedPost" @navigate="handleNavigate" />

      <!-- 联系页面 -->
      <Contact v-else-if="currentView === 'contact'" />
    </main>
  </div>
</template>

<script>
import { ref } from 'vue'
import Sidebar from './components/Sidebar.vue'
import Button from './components/Button.vue'
import MatrixBackground from './components/MatrixBackground.vue'
import Home from './components/Home.vue'
import Projects from './components/Projects.vue'
import BuffotteReport from './components/BuffotteReport.vue'
import About from './components/About.vue'
import Blog from './components/Blog.vue'
import PostDetail from './components/PostDetail.vue'
import Contact from './components/Contact.vue'
import './css/app.css'

export default {
  components: {
    Sidebar,
    Button,
    MatrixBackground,
    Home,
    Projects,
    BuffotteReport,
    About,
    Blog,
    PostDetail,
    Contact
  },
  setup() {
    const currentView = ref('home')
    const selectedPost = ref(null)

    const handleNavigate = (view) => {
      console.log('导航到:', view)
      if (typeof view === 'object' && view.view) {
        currentView.value = view.view
        selectedPost.value = view.post
      } else {
        currentView.value = view
        selectedPost.value = null
      }
      console.log('currentView set to:', currentView.value)
    }

    return {
      currentView,
      selectedPost,
      handleNavigate
    }
  }
}
</script>
